# Generated by Django 5.1.3 on 2024-12-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_city_order_company_name_order_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='postal_code',
            new_name='zip_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='zip_code',
        ),
    ]
